language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global: 
    - # Bintray Environment variables for deployment
    - secure: "jx6aAnN+gGYR0TR23ovQ9wIa4t4iFqHbdLYv0gbjhKxEqjFpkdxqKIZgSxcoKY7rmMuEXYqAv4JTbahdi3JelkRanhCWsMjTpu+4f0rAkyoHGrl3WsLIiGK0M0YeLFeyXbGWUXEj+KToCJ1ILvMT6olpCBdLljCfXV4XRikxLOT5Yqcht0hbchOKrlyTaJlEU9Xk53RsOgQhBmLUuD6Bb1yTTLRFCt5QUvu4Nep94CYMmaHujRYAmE4JScc/PQtTdM3pdG9aa5OiIZ5te7kpVJhpTJ43+Nu09tNxSHSokxbQ+Y75BEjaOqX2IKJb94esqJ9tyra8fBetdb/oLdoKFHQj2XnlaPtyOHYVj95imgffOUmMufxIwpGgNRauFOc3THJW7ii3/EMv1S2/OS84N3gmtuslZXpcWPA+ArM5sIoVgLDubIV5m1ZKG6J68P6bJD+FOFm+Kun9ghd0ISfT90qgvCpypNVhSBacaiefW1xz4nkqceR6GQmSimeMcKeyYqZdbxxtaDDThgaw7m8TMCcZ8BC/prc85MtlW5STzu8P0OGFqo03JApGyFNHjfXQdeuzGFJBMl72bsL8QGsvEDwWG28qGs7fFsuUgJeDmhCybCiVe+r0oRW5EpMNXaAVQu+lCT5j3lu0ZZW5BzLPl+nEuOyxi7rcwuoIbqxFFcQ="
    - secure: "YlIXneDSN5s9Rwtefa+McboGMqLhUur6dx7nqgEbD3+25dc3zRqt6rrALXVT49wsKpVTWk5JCMKGQKe8wirw5fn9dbhKOxlmiF/9aNSiyAaqmL7f/jpXorduvN7gSuyu/Yax7E286/1VI/3Ddi41AU//pjloVP75NfEhZkJpCtO2DVA5bepcPKGQn6dB7uwEcJKyack1A6NX/owVGL5C9adZaRj5WpQFnEX1lqKNgi1zxWHUtsaxI09pO4DrLD49MrZa4LBBrATHJu8jgP9WXXEjZJO8PBDh/0T1X/Yoz6ZbajWaflZVTIcV83j6idsZWtPCADFTp5QLPckmpYD90OmA3tLXm/QcZe0I9NfG5fhxVMogDgoZ66Qya+A0aPYmAaxaPhSsasSit0a5Oey/yjtJnrxepjcMPNtjaxBUlGFdS/AZSVZ+QAqhwz8Dq1In9GNswrC5DVY49Q0ntJhrbKu55c+MbLI8+ZpTuq1Z+EQCMYkbirrTFQL5rIJk3gtRMDdMD7UAR1FusdpAB3yo8erey2ODU3IQsknvVRcD6eRn39WxBXy0AEtIZXA+JcFdLkOR7cEeBn6//Nk42dn5Z8q+PdlTWybdQ7b+UkjxpkhprjWSfWwk582/whs23ET5Vwth5PaE9RRP9+GDU3J09RQCoIT1ZXl06i4yKTq0z6E="
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis-publishOnRelease.sh
